package todo.TrainingProjects.logicUpgrade.projecteuler;

//          Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Problem002 {

    public static void main(String[] args) {
        int n1 = 0;
        int n2 = 1;
        int fibonacciValue = n1 + n2;
        int result = 0;

        while (fibonacciValue < 4000000) {
//            System.out.println(fibonacciValue);
            if (fibonacciValue % 2 == 0) {
                result += fibonacciValue;
            }

            n1 = n2;
//            System.out.println("n1 = n2 : " + (n1 = n2));
            n2 = fibonacciValue;
//            System.out.println("n2 = fibonacciValue : " +(n2 = fibonacciValue));
            fibonacciValue = n1 + n2;
//            System.out.println("fibonacciValue = n1 + n2 : " + (fibonacciValue = n1 + n2));
        }
        System.out.println("result = " + result);

    }
}

